
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Data Center 
subtitle: Vu Quang Nguyen 
url: https://vuquangnguyen2018.github.io/
baseurl: /DataCenter/
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
